USE AdventureWorks2019
GO

SELECT DATEDIFF(YEAR, GETDATE(), DATEADD(YEAR, 20, GETDATE())) --SECOND DATE - FIRST DATE -20, earlier date should come first- think it as range
	, DATEDIFF(YEAR, '1995-07-26', GETDATE()) as AGE
	,GETDATE()
	,DATEADD(MINUTE, 20, GETDATE())  
	,DATEADD(MINUTE, -20, GETDATE()) 
	,DATEADD(HOUR, -20, GETDATE())
	,DATEADD(SECOND, -20, GETDATE())
	,DATEADD(DAY, -20, GETDATE())
	,DATEADD(WEEK, -20, GETDATE())
	,DATEADD(MONTH, -20, GETDATE())
	,DATEADD(YEAR, -20, GETDATE())









